### ISSUE TITLE
images not appearing

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#964] opened 2018-02-13 19:26 UTC
the icon of the selected healthsite itself 
the main strap line logo
the icons on the about section
https://88.99.148.103/#about
data life cycle image missing arrows
https://88.99.148.103/#lifecycle

https://healthsites.io/static/img/globe.svg seems to have changed to https://88.99.148.103/image.png

**Comment by nixilla** [comment] 2019-02-11 16:47
Can't reproduce. It seems it's fixed now.

**Closed by nixilla** 2019-02-11 16:47 UTC
Labels: bug
