### ISSUE TITLE
Healthsites.io seems to remove data from OSM without user knowing it

### ISSUE THREAD

**Issue by nixilla** [healthsites/healthsites#1357] opened 2020-03-18 09:42 UTC
I've made some changes to 2 hospitals in UK which I know of. Just basic staff - contacts, addresses, urls and immediately I got comments from OSM community that some data has been removed.

Here is the changeset I've made: https://www.openstreetmap.org/changeset/82313659

Comments from community:

1) is there are reason you deleted the wikidata link or was it an accident?
2) the polygon from which you removed the building tag appears to correspond to the main hospital building in aerial imagery, so I do not believe this should have been removed.
3) After doing a test edit on another object with Healthsites.io, it appears that it simply deletes any tags which the application is not aware of, so this is not the mapper's fault.

I believe fixing this is now priority.

**Comment by meomancer** [comment] 2020-03-19 03:59
hi @nixilla 
this PR will fix this
https://github.com/healthsites/healthsites/pull/1359

**Comment by maning** [comment] 2020-03-21 09:34
The PR was merged, was this already in production?  I tested it yesterday and I got the same behavior.  See v5 of this way: https://pewu.github.io/osm-history/#/way/117630731

**Comment by vinber** [comment] 2020-03-21 13:41
it's not working, i just try it and it continue to erase data !

https://osmcha.org/changesets/82459520/

I corrected data (https://osmcha.org/changesets/82459682/) but please avoid edition !

**Comment by woodpeck** [comment] 2020-03-21 16:27
This is a grave bug and you must immediately disable all OSM editing until it is fixed. Also, you (i.e. the healthsites.io team) will have to find and correct all these data loss problems introduced into OSM. Please contact data@osmfoundation.org outlining your plan for this. Absent a convincing plan to repair the damage I am afraid we will have to revert any and all edits made to OpenStreetMap by healthsites.io.

**Comment by timlinux** [comment] 2020-03-22 07:33
@woodpeck thank you for your message - yes we will take all needed action to fix this ASAP

**Comment by meomancer** [comment] 2020-03-22 08:28
hi @woodpeck 
the editing is disabled for now
i will check and tested for tomorrow

**Comment by timlinux** [comment] 2020-03-22 08:37
@woodpeck @maning I have assembled a list of potentially affected records here:




- [ ] https://osmcha.org/changesets/82308472?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82316615?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82320334?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82339303?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82365972?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82423590?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82424501?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82425186?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82438289?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82449308?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82458349?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82459520?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82463928?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82465104?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82466226?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82466384?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82466742?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D
- [ ] https://osmcha.org/changesets/82466997?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22Healthsites.io%22%2C%22value%22%3A%22Healthsites.io%22%7D%5D%7D

**Comment by markherringer** [comment] 2020-03-22 13:31
Dear OSM Moderators

Thank you for raising the issue with data loss caused by edits through Healthsites.io. Our project is an important focal point for people looking to create, edit, visualise and extract data health facility data from OSM - especially in this trying time with COVID-19. We have fixed the underlying issues and also corrected any data issues that arose because of this issue.  Our team is on standby and will move to rapidly resolve any problems surfaced by the OSM community
.
A detailed list of data fixes we have done is available here:  https://github.com/healthsites/healthsites/issues/1357#issuecomment-602165455 

Thank you everyone,
Keep Safe
Regards

The Healthsites.io Team

**Comment by camelCaseNick** [comment] 2020-03-23 22:48
@timlinux What do you mean with _seems to be a legitimate change_? The changeset removed `healthcare=doctor` and in contrast to the tag in wider use (`amenity=doctors`) was proposed and approved. Whether to ignore proposals and go for a different tag should be up to a user – it should definitely not be decided by an editor software.

**Comment by timlinux** [comment] 2020-03-24 10:04
Thanks to those who gave input here. Based on further feedback from the data working group, we have also added a step in the edit / create form to require the changeset source and comment, whilst removing source attribute for the facility itself from our form.

<img width="621" alt="image" src="https://user-images.githubusercontent.com/178003/77413088-b9fc0c00-6db6-11ea-9f1c-2586125387c3.png">

The validator will force the comment and source to be at least 10 characters so that we can try to ensure they are descriptive.

New edits will have the following in their changeset (example):

https://www.openstreetmap.org/changeset/82563539

![Screenshot 2020-03-24 at 10 01 34](https://user-images.githubusercontent.com/178003/77412928-83be8c80-6db6-11ea-871b-32ccbb2ce45a.png)


```xml
<osm version="0.6" generator="CGImap 0.8.1 (5983 thorn-02.openstreetmap.org)" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
<changeset id="82563539" created_at="2020-03-24T09:54:47Z" closed_at="2020-03-24T09:54:47Z" open="false" user="timlinux" uid="381972" min_lat="39.4145087" min_lon="-7.3499796" max_lat="39.4145087" max_lon="-7.3499796" comments_count="0" changes_count="1">
<tag k="created_by" v="Healthsites.io (osmapi/1.2.2)"/>
<tag k="source" v="personal knowledge"/>
<tag k="comment" v="Updated to indicate the electricity supply source"/>
</changeset>
</osm>
```



See also #1384 and #1385

**Comment by timlinux** [comment] 2020-03-24 10:09
> @timlinux What do you mean with _seems to be a legitimate change_? The changeset removed `healthcare=doctor` and in contrast to the tag in wider use (`amenity=doctors`) was proposed and approved. Whether to ignore proposals and go for a different tag should be up to a user – it should definitely not be decided by an editor software.

Ok sorry, you are correct. I have fixed that one too and updated the list above accordingly. See https://www.openstreetmap.org/changeset/82564223

**Comment by timlinux** [comment] 2020-03-24 10:10
I am closing this issue. Thank you to all who contributed here.

**Closed by timlinux** 2020-03-24 10:10 UTC
Labels: OSM-editing-module, bug

**Comment by tyrasd** [comment] 2020-03-24 11:05
@timlinux how did you come up with the list of affected changesets above? I think there could be more than just these, for example I immediately found the following edit:

* https://osmcha.org/changesets/76265826/ removed the `addr:*`, `building`, `wikidata`, and many more tags on https://osm.org/way/25785564.

**Comment by timlinux** [comment] 2020-03-24 11:13
hi @tyrasd I used a search on oscha using Editor = Healthsites.io

![image](https://user-images.githubusercontent.com/178003/77419485-61ca0780-6dc0-11ea-97ae-c6512d35c3ee.png)

**Comment by timlinux** [comment] 2020-03-24 11:16
@tyrasd Thanks for the hint - we will go through the edits from that earlier work and make sure nothing gets lost.
